[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "ipc:///home/nick/soft/adaptive_sampling_scripts/saur10_human90_no_shear"
port = 5555
align_ref = "/home/nick/adaptive_sampling/refs/ref.mmi"

[conditions]
reference = "/home/nick/adaptive_sampling/refs/ref.mmi"

[conditions.0]
name = "deplete contaminants"
control = false
min_chunks = 0
max_chunks = inf
targets = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","MT","X","Y"]
single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"

[conditions.1]
name = "control condtion"
control = true
min_chunks = 0
max_chunks = inf
targets = []
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "stop_receiving"
no_map = "stop_receiving"
